# Generated by Django 5.1.1 on 2024-09-10 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_menuitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]